/********************************************************************************
** Form generated from reading UI file 'myclass.ui'
**
** Created by: Qt User Interface Compiler version 5.4.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MYCLASS_H
#define UI_MYCLASS_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_MyClassClass
{
public:
    QFrame *frame1;
    QLabel *label1;
    QPushButton *beginButton;
    QFrame *frame2;
    QLabel *label2;
    QFrame *frame3;
    QLabel *label3;
    QFrame *frame4;
    QLabel *label4;
    QFrame *frame5;
    QLabel *label5;
    QFrame *frame6;
    QLabel *label6;
    QFrame *frame7;
    QLabel *label7;
    QFrame *frame8;
    QLabel *label8;
    QFrame *frame9;
    QLabel *label9;
    QFrame *frame10;
    QLabel *label10;
    QFrame *frame11;
    QLabel *label11;
    QFrame *frame12;
    QLabel *label12;
    QFrame *frame13;
    QLabel *label13;
    QFrame *frame14;
    QLabel *label14;
    QFrame *frame15;
    QLabel *label15;
    QFrame *frame16;
    QLabel *label16;
    QLabel *label;
    QLineEdit *lineEdit_score;
    QLabel *label_display;

    void setupUi(QDialog *MyClassClass)
    {
        if (MyClassClass->objectName().isEmpty())
            MyClassClass->setObjectName(QStringLiteral("MyClassClass"));
        MyClassClass->resize(356, 254);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush1(QColor(228, 240, 255, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        MyClassClass->setPalette(palette);
        frame1 = new QFrame(MyClassClass);
        frame1->setObjectName(QStringLiteral("frame1"));
        frame1->setGeometry(QRect(10, 10, 54, 54));
        QFont font;
        font.setPointSize(14);
        font.setBold(true);
        font.setWeight(75);
        frame1->setFont(font);
        frame1->setFrameShape(QFrame::StyledPanel);
        frame1->setFrameShadow(QFrame::Raised);
        frame1->setLineWidth(7);
        label1 = new QLabel(frame1);
        label1->setObjectName(QStringLiteral("label1"));
        label1->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette1;
        QBrush brush2(QColor(0, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        label1->setPalette(palette1);
        QFont font1;
        font1.setFamily(QStringLiteral("Comic Sans MS"));
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setWeight(75);
        label1->setFont(font1);
        label1->setAutoFillBackground(true);
        label1->setFrameShape(QFrame::StyledPanel);
        label1->setFrameShadow(QFrame::Plain);
        label1->setTextFormat(Qt::RichText);
        label1->setAlignment(Qt::AlignCenter);
        beginButton = new QPushButton(MyClassClass);
        beginButton->setObjectName(QStringLiteral("beginButton"));
        beginButton->setGeometry(QRect(260, 10, 81, 51));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush3(QColor(255, 85, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush4(QColor(120, 120, 120, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        beginButton->setPalette(palette2);
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        beginButton->setFont(font2);
        beginButton->setAutoFillBackground(true);
        beginButton->setFlat(true);
        frame2 = new QFrame(MyClassClass);
        frame2->setObjectName(QStringLiteral("frame2"));
        frame2->setGeometry(QRect(70, 10, 54, 54));
        frame2->setFont(font);
        frame2->setFrameShape(QFrame::StyledPanel);
        frame2->setFrameShadow(QFrame::Raised);
        frame2->setLineWidth(7);
        label2 = new QLabel(frame2);
        label2->setObjectName(QStringLiteral("label2"));
        label2->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label2->setPalette(palette3);
        label2->setFont(font1);
        label2->setAutoFillBackground(true);
        label2->setFrameShape(QFrame::StyledPanel);
        label2->setTextFormat(Qt::RichText);
        label2->setAlignment(Qt::AlignCenter);
        frame3 = new QFrame(MyClassClass);
        frame3->setObjectName(QStringLiteral("frame3"));
        frame3->setGeometry(QRect(130, 10, 54, 54));
        frame3->setFont(font);
        frame3->setFrameShape(QFrame::StyledPanel);
        frame3->setFrameShadow(QFrame::Raised);
        frame3->setLineWidth(7);
        label3 = new QLabel(frame3);
        label3->setObjectName(QStringLiteral("label3"));
        label3->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label3->setPalette(palette4);
        label3->setFont(font1);
        label3->setAutoFillBackground(true);
        label3->setFrameShape(QFrame::StyledPanel);
        label3->setTextFormat(Qt::RichText);
        label3->setAlignment(Qt::AlignCenter);
        frame4 = new QFrame(MyClassClass);
        frame4->setObjectName(QStringLiteral("frame4"));
        frame4->setGeometry(QRect(190, 10, 54, 54));
        frame4->setFont(font);
        frame4->setFrameShape(QFrame::StyledPanel);
        frame4->setFrameShadow(QFrame::Raised);
        frame4->setLineWidth(7);
        label4 = new QLabel(frame4);
        label4->setObjectName(QStringLiteral("label4"));
        label4->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label4->setPalette(palette5);
        label4->setFont(font1);
        label4->setAutoFillBackground(true);
        label4->setFrameShape(QFrame::StyledPanel);
        label4->setTextFormat(Qt::RichText);
        label4->setAlignment(Qt::AlignCenter);
        frame5 = new QFrame(MyClassClass);
        frame5->setObjectName(QStringLiteral("frame5"));
        frame5->setGeometry(QRect(10, 70, 54, 54));
        frame5->setFont(font);
        frame5->setFrameShape(QFrame::StyledPanel);
        frame5->setFrameShadow(QFrame::Raised);
        frame5->setLineWidth(7);
        label5 = new QLabel(frame5);
        label5->setObjectName(QStringLiteral("label5"));
        label5->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label5->setPalette(palette6);
        label5->setFont(font1);
        label5->setAutoFillBackground(true);
        label5->setFrameShape(QFrame::StyledPanel);
        label5->setTextFormat(Qt::RichText);
        label5->setAlignment(Qt::AlignCenter);
        frame6 = new QFrame(MyClassClass);
        frame6->setObjectName(QStringLiteral("frame6"));
        frame6->setGeometry(QRect(70, 70, 54, 54));
        frame6->setFont(font);
        frame6->setFrameShape(QFrame::StyledPanel);
        frame6->setFrameShadow(QFrame::Raised);
        frame6->setLineWidth(7);
        label6 = new QLabel(frame6);
        label6->setObjectName(QStringLiteral("label6"));
        label6->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label6->setPalette(palette7);
        label6->setFont(font1);
        label6->setAutoFillBackground(true);
        label6->setFrameShape(QFrame::StyledPanel);
        label6->setTextFormat(Qt::RichText);
        label6->setAlignment(Qt::AlignCenter);
        frame7 = new QFrame(MyClassClass);
        frame7->setObjectName(QStringLiteral("frame7"));
        frame7->setGeometry(QRect(130, 70, 54, 54));
        frame7->setFont(font);
        frame7->setFrameShape(QFrame::StyledPanel);
        frame7->setFrameShadow(QFrame::Raised);
        frame7->setLineWidth(7);
        label7 = new QLabel(frame7);
        label7->setObjectName(QStringLiteral("label7"));
        label7->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label7->setPalette(palette8);
        label7->setFont(font1);
        label7->setAutoFillBackground(true);
        label7->setFrameShape(QFrame::StyledPanel);
        label7->setTextFormat(Qt::RichText);
        label7->setAlignment(Qt::AlignCenter);
        frame8 = new QFrame(MyClassClass);
        frame8->setObjectName(QStringLiteral("frame8"));
        frame8->setGeometry(QRect(190, 70, 54, 54));
        frame8->setFont(font);
        frame8->setFrameShape(QFrame::StyledPanel);
        frame8->setFrameShadow(QFrame::Raised);
        frame8->setLineWidth(7);
        label8 = new QLabel(frame8);
        label8->setObjectName(QStringLiteral("label8"));
        label8->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label8->setPalette(palette9);
        label8->setFont(font1);
        label8->setAutoFillBackground(true);
        label8->setFrameShape(QFrame::StyledPanel);
        label8->setTextFormat(Qt::RichText);
        label8->setAlignment(Qt::AlignCenter);
        frame9 = new QFrame(MyClassClass);
        frame9->setObjectName(QStringLiteral("frame9"));
        frame9->setGeometry(QRect(10, 130, 54, 54));
        frame9->setFont(font);
        frame9->setFrameShape(QFrame::StyledPanel);
        frame9->setFrameShadow(QFrame::Raised);
        frame9->setLineWidth(7);
        label9 = new QLabel(frame9);
        label9->setObjectName(QStringLiteral("label9"));
        label9->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label9->setPalette(palette10);
        label9->setFont(font1);
        label9->setAutoFillBackground(true);
        label9->setFrameShape(QFrame::StyledPanel);
        label9->setTextFormat(Qt::RichText);
        label9->setAlignment(Qt::AlignCenter);
        frame10 = new QFrame(MyClassClass);
        frame10->setObjectName(QStringLiteral("frame10"));
        frame10->setGeometry(QRect(70, 130, 54, 54));
        frame10->setFont(font);
        frame10->setFrameShape(QFrame::StyledPanel);
        frame10->setFrameShadow(QFrame::Raised);
        frame10->setLineWidth(7);
        label10 = new QLabel(frame10);
        label10->setObjectName(QStringLiteral("label10"));
        label10->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label10->setPalette(palette11);
        label10->setFont(font1);
        label10->setAutoFillBackground(true);
        label10->setFrameShape(QFrame::StyledPanel);
        label10->setTextFormat(Qt::RichText);
        label10->setAlignment(Qt::AlignCenter);
        frame11 = new QFrame(MyClassClass);
        frame11->setObjectName(QStringLiteral("frame11"));
        frame11->setGeometry(QRect(130, 130, 54, 54));
        frame11->setFont(font);
        frame11->setFrameShape(QFrame::StyledPanel);
        frame11->setFrameShadow(QFrame::Raised);
        frame11->setLineWidth(7);
        label11 = new QLabel(frame11);
        label11->setObjectName(QStringLiteral("label11"));
        label11->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label11->setPalette(palette12);
        label11->setFont(font1);
        label11->setAutoFillBackground(true);
        label11->setFrameShape(QFrame::StyledPanel);
        label11->setTextFormat(Qt::RichText);
        label11->setAlignment(Qt::AlignCenter);
        frame12 = new QFrame(MyClassClass);
        frame12->setObjectName(QStringLiteral("frame12"));
        frame12->setGeometry(QRect(190, 130, 54, 54));
        frame12->setFont(font);
        frame12->setFrameShape(QFrame::StyledPanel);
        frame12->setFrameShadow(QFrame::Raised);
        frame12->setLineWidth(7);
        label12 = new QLabel(frame12);
        label12->setObjectName(QStringLiteral("label12"));
        label12->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label12->setPalette(palette13);
        label12->setFont(font1);
        label12->setAutoFillBackground(true);
        label12->setFrameShape(QFrame::StyledPanel);
        label12->setTextFormat(Qt::RichText);
        label12->setAlignment(Qt::AlignCenter);
        frame13 = new QFrame(MyClassClass);
        frame13->setObjectName(QStringLiteral("frame13"));
        frame13->setGeometry(QRect(10, 190, 54, 54));
        frame13->setFont(font);
        frame13->setFrameShape(QFrame::StyledPanel);
        frame13->setFrameShadow(QFrame::Raised);
        frame13->setLineWidth(7);
        label13 = new QLabel(frame13);
        label13->setObjectName(QStringLiteral("label13"));
        label13->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label13->setPalette(palette14);
        label13->setFont(font1);
        label13->setAutoFillBackground(true);
        label13->setFrameShape(QFrame::StyledPanel);
        label13->setTextFormat(Qt::RichText);
        label13->setAlignment(Qt::AlignCenter);
        frame14 = new QFrame(MyClassClass);
        frame14->setObjectName(QStringLiteral("frame14"));
        frame14->setGeometry(QRect(70, 190, 54, 54));
        frame14->setFont(font);
        frame14->setFrameShape(QFrame::StyledPanel);
        frame14->setFrameShadow(QFrame::Raised);
        frame14->setLineWidth(7);
        label14 = new QLabel(frame14);
        label14->setObjectName(QStringLiteral("label14"));
        label14->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label14->setPalette(palette15);
        label14->setFont(font1);
        label14->setAutoFillBackground(true);
        label14->setFrameShape(QFrame::StyledPanel);
        label14->setTextFormat(Qt::RichText);
        label14->setAlignment(Qt::AlignCenter);
        frame15 = new QFrame(MyClassClass);
        frame15->setObjectName(QStringLiteral("frame15"));
        frame15->setGeometry(QRect(130, 190, 54, 54));
        frame15->setFont(font);
        frame15->setFrameShape(QFrame::StyledPanel);
        frame15->setFrameShadow(QFrame::Raised);
        frame15->setLineWidth(7);
        label15 = new QLabel(frame15);
        label15->setObjectName(QStringLiteral("label15"));
        label15->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette16.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette16.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette16.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label15->setPalette(palette16);
        label15->setFont(font1);
        label15->setAutoFillBackground(true);
        label15->setFrameShape(QFrame::StyledPanel);
        label15->setTextFormat(Qt::RichText);
        label15->setAlignment(Qt::AlignCenter);
        frame16 = new QFrame(MyClassClass);
        frame16->setObjectName(QStringLiteral("frame16"));
        frame16->setGeometry(QRect(190, 190, 54, 54));
        frame16->setFont(font);
        frame16->setFrameShape(QFrame::StyledPanel);
        frame16->setFrameShadow(QFrame::Raised);
        frame16->setLineWidth(7);
        label16 = new QLabel(frame16);
        label16->setObjectName(QStringLiteral("label16"));
        label16->setGeometry(QRect(0, 0, 54, 54));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette17.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette17.setBrush(QPalette::Active, QPalette::Text, brush2);
        palette17.setBrush(QPalette::Active, QPalette::ButtonText, brush2);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette17.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette17.setBrush(QPalette::Inactive, QPalette::Text, brush2);
        palette17.setBrush(QPalette::Inactive, QPalette::ButtonText, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette17.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        label16->setPalette(palette17);
        label16->setFont(font1);
        label16->setAutoFillBackground(true);
        label16->setFrameShape(QFrame::StyledPanel);
        label16->setTextFormat(Qt::RichText);
        label16->setAlignment(Qt::AlignCenter);
        label = new QLabel(MyClassClass);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(260, 70, 81, 21));
        label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_score = new QLineEdit(MyClassClass);
        lineEdit_score->setObjectName(QStringLiteral("lineEdit_score"));
        lineEdit_score->setGeometry(QRect(260, 100, 81, 31));
        lineEdit_score->setFocusPolicy(Qt::NoFocus);
        lineEdit_score->setFrame(true);
        lineEdit_score->setEchoMode(QLineEdit::Normal);
        lineEdit_score->setReadOnly(true);
        label_display = new QLabel(MyClassClass);
        label_display->setObjectName(QStringLiteral("label_display"));
        label_display->setGeometry(QRect(260, 150, 81, 91));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Base, brush);
        palette18.setBrush(QPalette::Active, QPalette::Window, brush2);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Window, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette18.setBrush(QPalette::Disabled, QPalette::Base, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::Window, brush2);
        label_display->setPalette(palette18);
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221 Light"));
        font3.setPointSize(20);
        font3.setBold(true);
        font3.setWeight(75);
        label_display->setFont(font3);
        label_display->setAutoFillBackground(true);
        label_display->setTextFormat(Qt::AutoText);
        label_display->setAlignment(Qt::AlignCenter);

        retranslateUi(MyClassClass);

        QMetaObject::connectSlotsByName(MyClassClass);
    } // setupUi

    void retranslateUi(QDialog *MyClassClass)
    {
        MyClassClass->setWindowTitle(QApplication::translate("MyClassClass", "\350\277\252\345\217\2242048", 0));
        label1->setText(QString());
        beginButton->setText(QApplication::translate("MyClassClass", "\345\274\200\345\247\213", 0));
        label2->setText(QString());
        label3->setText(QString());
        label4->setText(QString());
        label5->setText(QString());
        label6->setText(QString());
        label7->setText(QString());
        label8->setText(QString());
        label9->setText(QString());
        label10->setText(QString());
        label11->setText(QString());
        label12->setText(QString());
        label13->setText(QString());
        label14->setText(QString());
        label15->setText(QString());
        label16->setText(QString());
        label->setText(QApplication::translate("MyClassClass", "\345\210\206\346\225\260", 0));
        lineEdit_score->setText(QString());
        label_display->setText(QApplication::translate("MyClassClass", "2048", 0));
    } // retranslateUi

};

namespace Ui {
    class MyClassClass: public Ui_MyClassClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MYCLASS_H
